from google.api_core.client_options import ClientOptions
from google.cloud import discoveryengine_v1 as discoveryengine
from google.adk.tools import FunctionTool
import os

# Definition of a tool that accesses a Vertex AI Search Datastore
#
# This is based on code provided by Google at
# https://cloud.google.com/generative-ai-app-builder/docs/samples/genappbuilder-search
#
# Key changes from original:
# 1. Using ExtractiveContentSpec instead of just SnippetSpec for PDF documents
# 2. Extracting summary from response.summary.summary_text
# 3. Properly accessing extractive_answers and extractive_segments from derived_struct_data
#
# The object definitions aren't available to all IDEs because of Google's ProtoBuf
# implementation, so the IDE may generate a warning, but work fine. I've used
# dicts here instead, but indicated the Class that could be used instead.
# You can see the definitions at
# https://cloud.google.com/python/docs/reference/discoveryengine/latest/google.cloud.discoveryengine_v1.types

def search(
    project_id: str,
    location: str,
    engine_id: str,

    search_query: str,
    credentials=None,
) -> list[str]:
    """
    Search the Vertex AI Search datastore for information from PDF documents.
    
    Args:
        project_id: GCP project ID
        location: Location of the datastore (e.g., 'global' or 'us-central1')
        engine_id: The engine ID of the Vertex AI Search datastore
        search_query: The search query string
        
    Returns:
        List of search result strings containing relevant document excerpts
    """
    # For more information, refer to:
    # https://cloud.google.com/generative-ai-app-builder/docs/locations#specify_a_multi-region_for_your_data_store
    client_options = (
        ClientOptions(api_endpoint=f"{location}-discoveryengine.googleapis.com")
        if location != "global"
        else None
    )

    # Create a client
    client = discoveryengine.SearchServiceClient(
        client_options=client_options, 
        credentials=credentials
    )

    # The full resource name of the search app serving config
    serving_config = f"projects/{project_id}/locations/{location}/collections/default_collection/engines/{engine_id}/servingConfigs/default_config"

    # Create search request using discoveryengine.SearchRequest
    # Using ExtractiveContentSpec for PDF documents - this is CRITICAL for unstructured data
    # ExtractiveContentSpec returns verbatim text from the documents
    request = discoveryengine.SearchRequest(
        serving_config=serving_config,
        query=search_query,
        page_size=5,  # Limit results to top 5 for relevance
        content_search_spec=discoveryengine.SearchRequest.ContentSearchSpec(
            # SnippetSpec returns highlighted snippets
            snippet_spec=discoveryengine.SearchRequest.ContentSearchSpec.SnippetSpec(
                max_snippet_count=3,
                return_snippet=True,
            ),
            # ExtractiveContentSpec returns verbatim text from PDFs
            # This is essential for getting actual content from unstructured documents
            extractive_content_spec=discoveryengine.SearchRequest.ContentSearchSpec.ExtractiveContentSpec(
                max_extractive_answer_count=3,  # Get up to 3 extractive answers per result
                max_extractive_segment_count=3,  # Get up to 3 extractive segments per result
                return_extractive_segment_score=True,  # Include relevance scores
            ),
            # SummarySpec generates a summary of the search results
            summary_spec=discoveryengine.SearchRequest.ContentSearchSpec.SummarySpec(
                summary_result_count=5,  # Summarize top 5 results
                include_citations=True,  # Include citations for attribution
            ),
        ),
    )

    response = client.search(request=request)

    # Format and return the results
    results = []
    
    # First, try to get the summary if available (this is generated by the search service)
    # The summary is a high-level answer to the query based on the documents
    try:
        if response.summary and response.summary.summary_text:
            summary_text = response.summary.summary_text.strip()
            if summary_text:
                results.append(f"[Summary]: {summary_text}")
    except AttributeError:
        pass  # Summary not available
    
    # Process individual search results
    for result in response.results:
        document = result.document
        
        # Method 1: Get extractive answers and segments from derived_struct_data
        # This is the primary method for PDF/unstructured documents
        if hasattr(document, 'derived_struct_data') and document.derived_struct_data:
            derived_data = dict(document.derived_struct_data)
            
            # Extract extractive_answers (verbatim text that directly answers the query)
            if 'extractive_answers' in derived_data:
                for answer in derived_data['extractive_answers']:
                    if isinstance(answer, dict) and 'content' in answer:
                        content = answer['content'].strip()
                        if content:
                            results.append(f"[Answer]: {content}")
            
            # Extract extractive_segments (larger text chunks from documents)
            if 'extractive_segments' in derived_data:
                for segment in derived_data['extractive_segments']:
                    if isinstance(segment, dict) and 'content' in segment:
                        content = segment['content'].strip()
                        if content:
                            results.append(f"[Segment]: {content}")
            
            # Extract snippets if available
            if 'snippets' in derived_data:
                for snippet in derived_data['snippets']:
                    if isinstance(snippet, dict) and 'snippet' in snippet:
                        snippet_text = snippet['snippet'].strip()
                        if snippet_text:
                            results.append(f"[Snippet]: {snippet_text}")
        
        # Method 2: Get struct_data (for structured documents or fallback)
        if hasattr(document, 'struct_data') and document.struct_data:
            struct_dict = dict(document.struct_data)
            # Extract any text-like content from struct_data
            for key, value in struct_dict.items():
                if key.lower() in ['content', 'text', 'body', 'description', 'snippet']:
                    if value and str(value).strip():
                        results.append(f"[{key.title()}]: {str(value).strip()}")
    
    # If no results were found, return a helpful message
    if not results:
        return ["No relevant information found in the store documents for this query."]
    
    return results


def get_datastore_search_tool() -> FunctionTool:
    """
    Creates and returns a tool for searching the Vertex AI Search datastore.
    
    This tool allows the agent to answer questions about store hours, location,
    history, staff, and other store-specific information from uploaded PDF documents.
    
    Returns:
        FunctionTool instance configured for datastore search
    """
    def search_datastore(search_query: str) -> str:
        """
        Search the Vertex AI Search datastore for store-related information.

        Use this tool to find information about:
        - Store hours and operating schedule
        - Store location and address
        - Store history and background
        - Staff members and their expertise
        - Store policies and services

        Args:
            search_query: The query to search for in store documents.
                         Be specific and include relevant keywords.
                         Examples: "store hours Thursday", "who is Betty", "store location"

        Returns:
            Formatted string containing search results from store documents.
            Results include summaries, answers, and relevant excerpts from PDFs.
        """
        # Read env at call time so dotenv loads after tool creation still take effect.
        project_id = os.environ.get("DATASTORE_PROJECT_ID", os.environ.get("GOOGLE_CLOUD_PROJECT", ""))
        location = os.environ.get("DATASTORE_LOCATION", os.environ.get("GOOGLE_CLOUD_LOCATION", "global"))
        engine_id = os.environ.get("DATASTORE_ENGINE_ID", "")
        if not project_id or not engine_id:
            error_msg = (
                "Error: Datastore configuration is missing. Please check environment variables.\n"
                f"Current values - PROJECT_ID: {project_id or 'NOT SET'}, ENGINE_ID: {engine_id or 'NOT SET'}\n"
                "For Udacity setup, ensure you've set DATASTORE_PROJECT_ID and DATASTORE_ENGINE_ID in .env"
            )
            return error_msg
        
        try:
            results = search(project_id, location, engine_id, search_query)
            # Format results as a single string with clear separation
            if results:
                formatted_results = "\n---\n".join(results)
                return f"Search results for '{search_query}':\n\n{formatted_results}"
            else:
                return f"No relevant information found in the store documents for: {search_query}"
        except Exception as e:
            print(f"DEBUG: Datastore search error: {e}") # Added debug print
            error_msg = f"Error searching datastore: {str(e)}\n"
            # Provide helpful debugging information
            error_msg += f"Query: {search_query}\n"
            error_msg += f"Project ID: {project_id}\n"
            error_msg += f"Engine ID: {engine_id}\n"
            error_msg += f"Location: {location}\n"
            if "authentication" in str(e).lower() or "credential" in str(e).lower():
                error_msg += (
                    "\nAuthentication error detected. Ensure you've run:\n"
                    "gcloud auth application-default login\n"
                )
            elif "not found" in str(e).lower():
                error_msg += (
                    "\nResource not found. Check that:\n"
                    "1. The datastore engine ID is correct\n"
                    "2. The project ID is correct\n"
                    "3. The datastore has been created and indexed\n"
                )
            return error_msg
    
    # Create tool with proper description for the agent
    return FunctionTool(search_datastore)
